# -*- coding: utf-8 -*-
"""smtplib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7P_-cfJE0enS768pMwX736jZY1uX3GM

This is a practice of using the smtplib library, with which the smtp protocol is used to send messages

by: Jesus Alejandro Colin Vilchis
"""

#!pip install smtplib
import smtplib

message = """From: From christon Malliarak <jealcovi98@gmail.com>
            To: To Cristian <jealcovip@hotmail.es>
            Subject: STMP e-mail test SMTP

            This is my hello world
             """

server = smtplib.SMTP('orion.websitewelcome.com',587)

server.connect('orion.websitewelcome.com',587)

server.ehlo()

from auth import email, password
server.login(email, password) # the file is not shared

server.starttls() # secure protocol to encrypt
server.send("jealcovi98@gmail.com","jealcovip@hotmail.es",message)

server.quit()